# SETUP FOR VIDEO FILE
PATH_INPUT_DIR = '__YOUR_DIRECTORY__' # CHANGE
VIDEO_NAME = '__VIDEO_FILENAME_._EXTENSION__' # CHANGE

# SETUP FOR MESSAGE FILE
PATH_MESSAGE_FILE = 'messages.json' # CHANGE IF YOU WANT

# SETUP FOR EMOTION TRANSLATION FILE
PATH_EMOTION_TRANSLATION_FILE = 'emotion_translation.json' # CHANGE IF YOU WANT

# SETUP FOR WINDOW SIZE
DISPLAY_WIDTH = 1280 # CHANGE IF YOU WANT
DISPLAY_HEIGHT = 720 # CHANGE IF YOU WANT
